# Files path
paths:
  input_csv: "data/materials-2.csv"
  input_json: "data/test.json"
  raw_data_dir: "data/raw/"
  processed_data_dir: "data/processed/"
  quarantine_data_dir: "data/quarantine/"

# General configurations
spark:
  app_name: "MaterialsDataPipeline"
  master: "local[1]"  # Change to yarn or cluster

# Loading options
read_options:
  header: true
  inferSchema: false
  delimiter: ","
  multiline: true
  escape: '"'
  quote: '"'
  file_format: "csv"