# Files path
paths:
  input_csv: "data/materials-2.csv"
  raw_data_dir: "data/raw/"
  processed_data_dir: "data/processed/"
  quarantine_data_dir: "data/quarantine/"

# General configurations
spark:
  app_name: "MaterialsDataPipeline"
  master: "local[*]"  # Change to yarn or cluster

# Loading options
read_options:
  header: true
  inferSchema: false
  delimiter: ","